[tool.poetry]
name = "coding-challenge"
version = "0.1.0"
description = ""
authors = ["collin_furth <ccfurth2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
localstack = "^3.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
